active_zuora.gemspec
It appears Savon can be upgraded to 1.x versions without any change. I have tested the change with my project (>1000 Zuora specs).
I'm sceptical if this change is worthwhile though, since this is still a major version behind.
=> Upgrade Savon to v1.2.0

lib/active_zuora/persistence.rb, spec/account_integration_spec.rb, spec/spec_helper.rb
This PR is a suggested fix for https://github.com/sportngin/active_zuora/issues/29
All Zuora request and responses are zipped together instead of manually searched for, which handles the scenario of an error payload not containing a Zuora id.
=> [#29] Correctly populate error information

lib/active_zuora/persistence.rb
Fix the typo.
Since `fields_to_null` is used in `lib/persistence.rb` and it fits the api field name in Zuora, I think we should all use `fields_to_null`
=> Fix the typo :fields_to_nil -> :fields_to_null

lib/active_zuora/base.rb, spec/base_spec.rb
Quote from http://goo.gl/AiJeqa (First Comment)
> Please note that the order in which the fieldsToNull field appears in the SOAP request DOES matter.
> The following works:
```xml
<ns1:update>
<ns1:zObjects xsi:type="ns2:PaymentMethod">
<ns2:fieldsToNull>MandateReceived</ns2:fieldsToNull>
<ns2:Id>2c92c0f841ba8ff60141bcc626521637</ns2:Id>
</ns1:zObjects>
</ns1:update>
```
> But having the fieldsToNull field after Id does not.
=> Fix the fields order when building xml

README.md, lib/active_zuora.rb, lib/active_zuora/batch_subscribe.rb, lib/active_zuora/collection_proxy.rb, lib/active_zuora/generator.rb, spec/collection_proxy_spec.rb, spec/subscribe_integration_spec.rb
Per the Zuora docs https://knowledgecenter.zuora.com/D_SOAP_API/E_SOAP_API_Calls/subscribe_call
The subscribe() call bundles the information required to create one or more new subscriptions.
This pr aims to support creating multiple subscriptions at once.
The approach is to use a CollectionProxy - analogous to an ActiveRecord::Associations::CollectionProxy that includes a BatchSubscribe module.  The BatchSubscribe module has a batch_subscribe method that builds a subscribe xml from a collection.
=> support for batch subscribe requests

lib/active_zuora.rb, lib/active_zuora/generator.rb, lib/active_zuora/lazy_attr.rb, lib/active_zuora/relation.rb, spec/lazy_attr_spec.rb, spec/subscribe_integration_spec.rb
You can't query for more than one invoice at a time because the body field can only be queried for a single invoice. This PR sets up a lazy attribute concern that will query the api for a specific attribute when it's asked for by a user instead of during the initial collection query.
=> Add Support for lazy attributes that can't be queried via a relation

lib/active_zuora/generator.rb
The invoice payment data field on Payments is not valid for queries and was causing errors. This adds it to the exclusions list.
=> Fix #43 - Add invoice_payment_data to exclusions list

lib/active_zuora/generator.rb
Product Rate Plans must query for the Active Currencies field by itself. This excludes the field from normal queries and lazy loads it instead.
=> Lazy load Active Currencies on Product Rate Plans

lib/active_zuora/generator.rb, lib/active_zuora/lazy_attr.rb
Per the Zuora documentation (source: http://knowledgecenter.zuora.com/BC_Developers/SOAP_API/E1_SOAP_API_Object_Reference/RatePlanCharge):
`You can query for Price from a RatePlanCharge object unless the charge model is volume or tiered pricing. If the charged model is volume or tiered pricing, then you need to query for Price from the relevant RatePlanChargeTier.
`
What they fail to mention is when you include `Price` in a query to the Rate Plan Charge object, volume and tiered Rate plan charges will fail to be returned, not just not include a price attribute. I have made price a lazily loaded attribute to all Rate Plan Charges should be treated equally.
I think we might need to further wrap this to consistently return price no matter what the charge model.
=> Lazy load price.

lib/active_zuora/generator.rb
Zuora added the BillRunId attribute as a filter to [Invoices](https://knowledgecenter.zuora.com/BC_Developers/SOAP_API/E1_SOAP_API_Object_Reference/Invoice) in WSDL 66.0. This PR excludes this attribute from queries.
=> Exclude invoice bill_run_id from query

lib/active_zuora/generator.rb
The ProductRatePlanChargeId field is causing errors on InvoiceItem queries. This PR adds an exclusion for `product_rate_plan_charge_id`.
=> Add product_rate_plan_charge_id to exclusion list for InvoiceItem

README.md, lib/active_zuora/connection.rb, spec/connection_spec.rb, spec/subscribe_integration_spec.rb
As a Zuora user, I would like my custom headers to be included in all requests. 
* Customer headers are not being used for login action
* Adding the customer headers to the login soap request
* cleaning up some random spec failures caused by old object staying around. 
* Using before/after all to speed up integration spec a bit.
=> Use custom header for login

lib/active_zuora/connection.rb
This variable leads to confusion when reading the source code.
Now that the session expiration logic is handled through a SOAP
expection it no longer makes sense.
REF: https://github.com/sportngin/active_zuora/commit/3e910db1b113f22dd7409ce4c39e1529dcb4d772
=> Remove unused instance variable.

lib/active_zuora/relation.rb
Not all the objects define the `created_date` field, with this fix we check if the field is defined before setting the order attribute.
Fixes sportngin/active_zuora/issues/68
=> Set the order attribute only if the `created_date` field is defined.

active_zuora.gemspec
Belly has been running this change in a production Rails 5 app since September with no issues.
=> Bump gem dependencies to incorporate activesupport 5.0 and activemodel 5.0

lib/active_zuora/generator.rb
Update Account class relations to bill-to and sold-to contacts to use
the correct fields. Also add a missing relation to PaymentMethod via.
default_payment_method_id.
Addresses #72
=> Update account relations

lib/active_zuora/generator.rb
=> Exclude RevenueRecogntionRuleName from queries on RatePlanCharge

lib/active_zuora/relation.rb
The `response[:query_response][:result][:query_locator]` locator never changes - it always points to the second page. If there are more than 4k accounts in Zuora, the query method will keep loading the second page endlessly.
The correct `query_locator` to be used there is `query_response[:result][:query_locator]` which points to the next page, not to the second.
=> Make the query method use the correct query_locator

lib/active_zuora/generator.rb
The ProductDiscountApplyDetailData field is causing errors on ProductRatePlanCharge queries. This PR adds an exclusion for `product_discount_apply_detail_data`.
=> Exclude product_discount_apply_detail_data from query

lib/active_zuora/fields.rb, lib/active_zuora/relation.rb
Once upgrading to Rails 5.2 ActiveZuora is unable to return a `ActiveZuora::Relation` objects as the attempt to call `changed_attributes.clear` fails with the error: 
`RuntimeError: can't modify frozen ActiveSupport::HashWithIndifferentAccess`
Updating the code to utilize the method `clear_changes_information` works for 5.2 but is not backwards compatible. In an effort to keep backwards compatibility the conditional logic was added and it has been confirmed to still work for Rails 5.1.6.1 as well.
=> Update objectify_query_results 
